version: "3.8"
services:
    frontend:
        container_name: frontend_equeue
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_END=production
        stdin_open: true
        tty: true
